service: github-webhooks

plugins:
  - serverless-offline
  - serverless-secrets-plugin
  - serverless-plugin-resource-tagging

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: eu-west-1
  profile: mobilevikings-mas
  environment:
    GITHUB_WEBHOOK_SECRET: ${self:custom.secrets.GITHUB_WEBHOOK_SECRET}
    GITHUB_API_KEY: ${self:custom.secrets.GITHUB_API_KEY}
  stackTags:
    CreatedByt: "Serverless"
    Repo: "Serverless-functions"
    Service: "github-webhooks"

functions:
  fixupValidator:
    handler: handler.fixupCommits
    events:
      - http:
          path: github-fixups
          method: post
          cors: true
  pythonRequirementsValidator:
    handler: handler.pythonRequirements
    events:
      - http:
          path: github-python-requirements
          method: post
          cors: true
  openTasksValidator:
    handler: handler.openTasks
    events:
      - http:
          path: github-tasks
          method: post
          cors: true
